server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: pegasus-api-products
          uri: http://pegasus-api-products:8080
          predicates:
            - Path=/pegasus-api-products/**
          filters:
            - StripPrefix=1

        - id: service-b
          uri: http://service-b:8080
          predicates:
            - Path=/service-b/**
          filters:
            - StripPrefix=1
