  server:
    port: 8080

  spring:
    cloud:
      gateway:
        routes:
          - id: service-a
            uri: http://service-a:8080
            predicates:
              - Path=/service-a/**
            filters:
              - StripPrefix=1

          - id: service-b
            uri: http://service-b:8080
            predicates:
              - Path=/service-b/**
            filters:
              - StripPrefix=1
